### ISSUE TITLE
Breaks if offline during auth cycle

### ISSUE THREAD

**Issue by toddmedema** [googledrive/realtime-utils#6]
@sethhoward1988 We've gotten several user complaints that if they leave their window open and inactive for a long time, this stops working and fails silently. Which is really bad, because it's already resulted in several users losing hours of work :(

I was able to reproduce locally - after leaving the tab open overnight, the tab broke. On a heathy tab, changing the text hits `/save` and `/bind`. But, on the broken / timed out tab, neither of these network requests get made.

It gets even more interesting when looking at the JS console:

`Drive Realtime API Error: token_refresh_required: The OAuth token must be refreshed. drive.google.com/otservice/api:435`

Then:

```
Uncaught TypeError: Cannot read property 'authorize' of undefined   realtime-client-utils.js:166
    at onError (realtime-client-utils.js:166)
    at Object.ua (drive.google.com/otservice/api:435)
    at QA (drive.google.com/otservice/api:213)
    at Yv (drive.google.com/otservice/api:128)
    at Zh (drive.google.com/otservice/api:34)
    at Qt.d.Qa (drive.google.com/otservice/api:288)
    at eh.d.Lc (drive.google.com/otservice/api:298)
    at XMLHttpRequest.<anonymous> (drive.google.com/otservice/api:71)
    at XMLHttpRequest.<anonymous> (drive.google.com/otservice/api:426)
```

Which I'm guessing is the line where things go wrong. After that, it logs `Refreshed Auth Token` every 30 or so minutes, but even right after a token refresh, it still has the same behavior described above.

For the record, our repo: https://github.com/Fabricate-IO/expedition-quest-creator

You can try out the app at http://quests.expeditiongame.com

The file that handles the file uploading: https://github.com/Fabricate-IO/expedition-quest-creator/blob/master/app/actions/quest.tsx

Client user auth: https://github.com/Fabricate-IO/expedition-quest-creator/blob/master/app/actions/user.tsx

Server user auth: https://github.com/Fabricate-IO/expedition-quest-creator/blob/master/lib/oauth2.js

**Comment by toddmedema** [comment]
To clarify after running it past a friend, the drive uploading thing is actually working properly - it is, in fact, saving the files to drive fine. So the problem is specifically that realtime is losing sync

**Comment by toddmedema** [comment]
@sethhoward1988 think I figured out the root cause - looks like it specifically breaks if you're offline during the every-30-minute re-auth cycle, and then even if it re-auths after that, it fails to pick up changes

**Comment by sethmiles** [comment]
Feel free to send a patch, I won't be able to look at this for a few days.
